# Generated by Django 6.0.7 on 2026-07-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company / Brand Name"
                    ),
                ),
                (
                    "service_interest",
                    models.CharField(
                        choices=[
                            ("technology", "Technology Services (Software, AI, Cloud)"),
                            (
                                "digital_marketing",
                                "Digital Marketing (SEO, Performance)",
                            ),
                            ("social_media", "Social Media Marketing"),
                            ("web_development", "Web Development"),
                            ("mobile_app", "Mobile App Development"),
                            ("ui_ux", "UI/UX Design"),
                            ("brand_creative", "Creative & Brand Studio"),
                            (
                                "growth_partnership",
                                "Growth Partnership / Managed Growth",
                            ),
                            ("ecommerce", "E-Commerce & D2C Growth"),
                            ("automation_ai", "AI & Automation"),
                            ("orm", "Online Reputation Management"),
                            ("influencer", "Influencer Marketing"),
                            ("consultation", "Business Consultation"),
                            ("other", "Other / Not Sure"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Service Interested In",
                    ),
                ),
                (
                    "budget",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_25k", "Under ₹25,000/month"),
                            ("25k_50k", "₹25,000 – ₹50,000/month"),
                            ("50k_1L", "₹50,000 – ₹1,00,000/month"),
                            ("1L_3L", "₹1,00,000 – ₹3,00,000/month"),
                            ("above_3L", "Above ₹3,00,000/month"),
                            ("project_based", "Project-Based (One-Time)"),
                            ("discuss", "Prefer to Discuss"),
                        ],
                        default="discuss",
                        max_length=30,
                        verbose_name="Budget Range",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message / Requirements")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website_contact", "Website Contact Form"),
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("referral", "Referral"),
                            ("google_ads", "Google Ads"),
                            ("direct", "Direct"),
                            ("other", "Other"),
                        ],
                        default="website_contact",
                        max_length=30,
                        verbose_name="Lead Source",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiation", "In Negotiation"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("on_hold", "On Hold"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Lead Status",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Assigned To"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal Notes")),
                (
                    "auto_reply_sent",
                    models.BooleanField(default=False, verbose_name="Auto-Reply Sent?"),
                ),
                (
                    "team_notified",
                    models.BooleanField(default=False, verbose_name="Team Notified?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
