# Generated by Django 6.0.7 on 2026-07-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("client", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=100)),
                ("service", models.CharField(max_length=100)),
                ("challenge", models.TextField()),
                ("solution", models.TextField()),
                ("result_1_label", models.CharField(max_length=50)),
                ("result_1_value", models.CharField(max_length=50)),
                ("result_2_label", models.CharField(blank=True, max_length=50)),
                ("result_2_value", models.CharField(blank=True, max_length=50)),
                ("result_3_label", models.CharField(blank=True, max_length=50)),
                ("result_3_value", models.CharField(blank=True, max_length=50)),
                ("is_featured", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Case Study",
                "verbose_name_plural": "Case Studies",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="e.g. 'Clients Served'", max_length=100),
                ),
                ("value", models.CharField(help_text="e.g. '500+'", max_length=20)),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Company Stat",
                "verbose_name_plural": "Company Stats",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("services", "Services"),
                            ("process", "Process"),
                            ("pricing", "Pricing & Engagement"),
                            ("technology", "Technology"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "sub_verticals",
                    models.JSONField(default=list, help_text='["Sub 1", "Sub 2"]'),
                ),
                ("color", models.CharField(default="#8B2A4A", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technology", "Technology Services"),
                            ("digital_growth", "Digital Growth Services"),
                            ("creative", "Creative & Brand Studio"),
                            ("growth_partnership", "Growth Partnership"),
                        ],
                        max_length=30,
                    ),
                ),
                ("short_desc", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Lucide icon name e.g. Code2, Brain, Palette",
                        max_length=50,
                    ),
                ),
                (
                    "sub_services",
                    models.JSONField(
                        default=list, help_text='["Sub-service 1", "Sub-service 2"]'
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="maroon", help_text="Accent color class", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("avatar_initials", models.CharField(max_length=3)),
                (
                    "avatar_color",
                    models.CharField(
                        default="#8B2A4A", help_text="Hex color", max_length=7
                    ),
                ),
                ("service_used", models.CharField(blank=True, max_length=100)),
                ("is_featured", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
